version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dolibarr
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - dolibarr_network

  web:
    image: tuxgasy/dolibarr
    environment:
      DOLI_DB_HOST: mariadb
      DOLI_DB_USER: root
      DOLI_DB_PASSWORD: root
      DOLI_DB_NAME: dolibarr
      DOLI_URL_ROOT: 'http://localhost'
      PHP_INI_DATE_TIMEZONE: 'Europe/Paris'
      APACHE_SERVER_NAME: 'localhost'
    ports:
      - "80:80"
    volumes:
      - dolibarr_documents:/var/www/html/documents
    networks:
      - dolibarr_network
    depends_on:
      - mariadb
    command: >
      bash -c "echo 'ServerName localhost' >> /etc/apache2/conf-available/servername.conf &&
               a2enconf servername &&
               apache2-foreground &&
               service apache2 reload"

volumes:
  mariadb_data:
  dolibarr_documents:

networks:
  dolibarr_network:
